name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Create .env file
      run: |
        touch server/.env
        echo "DB_URI=${{ secrets.DB_URI }}" >> server/.env
        echo "JWT_TOKEN=${{ secrets.JWT_TOKEN }}" >> server/.env
        echo "PUBLIC_PATH=${{ secrets.PUBLIC_PATH }}" >> server/.env
        echo "MAX_FILE_UPLOAD_LIMIT=${{ secrets.MAX_FILE_UPLOAD_LIMIT }}" >> server/.env
        echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> server/.env
        echo "AWS_BUCKET_REGION=${{ secrets.AWS_BUCKET_REGION }}" >> server/.env
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> server/.env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> server/.env
        echo "IMAGE_URL=${{ secrets.IMAGE_URL }}" >> server/.env
        echo "ENVIROMENT=${{ secrets.ENVIROMENT }}" >> server/.env
    - name: Install dependencies and restart server
      run: |
        cd server
        npm install
        pm2 restart index.js
